### ISSUE TITLE
New option to config the page number style

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/incgraph#2]
Currently, the node style used by overlay options like `overlay page number at` is hard-coded.
https://github.com/T-F-S/incgraph/blob/4da8ba71695c506c922c367a5869fd39c27a245a/tex/latex/incgraph/incgraph.sty#L414-L419

How about storing these options into a new option, like `/igr/options` and `/igr/bookmark options`, so that users can configure the overlay page number style? For example,

```tex
\documentclass{article}
\usepackage{incgraph}
\usepackage{tikz}

% suggested new option "overlay page number options"
\makeatletter
\igrset{
  % define
  overlay page number options/.store in=\igc@overlay@pagenumber@options,
  % init
  overlay page number options={
    fill opacity=0.35,draw opacity=0.5,text opacity=1,
    inner xsep=1em,rounded corners,fill=white,draw=black
  },
  % apply
  overlay page number at/.style={
    overlay={
      \expandafter\node\expandafter[\igc@overlay@pagenumber@options] 
        at (#1) {\thepage};
    }
  },
}
\makeatother

% user additions
\usepackage{etoolbox}
\makeatletter
\igrset{
  overlay page number options app/.code={%
    \appto\igc@overlay@pagenumber@options{,#1}
  }
}
\makeatother


\begin{document}
\incgraph[overlay page number at bottom][page=1]{example-image-a}

\igrset{
  overlay page number options app={draw=none, fill opacity=1, font=\Huge}
}

\incgraph[overlay page number at bottom][page=1]{example-image-b}
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/88949724-33a48900-d2c6-11ea-9e80-f1731cb46ad9.png)

**Comment by T-F-S** [comment]
Your suggestion sounds very good to me. I have not done tests yet, but I do not expect problems with this feature.

If nothing comes up, I will add it to the next version. Thank your for providing this.

**Comment by T-F-S** [comment]
Implemented with version `1.2.0 (2021-10-20)`:
- Option `overlay page number options`

**Comment by muzimuzhi** [comment]
The initial value of `overlay page number options` is so long (a seven-item key-val list) and since usually users (if I'm not the only one) come up with need for incremental modification, I'm afraid the need for adding an option like `overlay page number options app` will soon arise.

As an example, personally I almost always use `tcolorbox` option `/tcb/minted options app` instead of `/tcb/minted options`, whose init value is a four-item kv list. My [original post](https://github.com/T-F-S/incgraph/issues/2#issue-668951562) even contained a proposal already.

Perhaps `pgfkeys` should support handlers like `/.store in append` and `/.store in prefix`, if it's not too late.

**Comment by T-F-S** [comment]
Hmm, seems I underestimated the need for `overlay page number options app`...

But, I will add such an option for the next version.

**Comment by T-F-S** [comment]
Implemented in https://github.com/T-F-S/incgraph/releases/tag/v1.3.0
