### ISSUE TITLE
[doc] missing short verb |...|

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/incgraph#3]
In the doc of choice option `paper`, short verb `|...|` is missing from its last four possible values. See line 400:
https://github.com/T-F-S/incgraph/blob/4da8ba71695c506c922c367a5869fd39c27a245a/doc/latex/incgraph/incgraph.tex#L392-L401

**Comment by T-F-S** [comment]
Yes, you are right. I will correct that.

**Comment by T-F-S** [comment]
Corrected with version `1.2.0 (2021-10-20)`.
