### ISSUE TITLE
Doc typo in v1.2.0

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/incgraph#4]
https://github.com/T-F-S/incgraph/blob/c7f076432a83106e3953dca700482cfeb42966d9/doc/latex/incgraph/incgraph.tex#L389-L391

Not sure but perhaps

"..., i.e. the underlying <cmd> is called directly <s>any</s>and may ..."

**Comment by T-F-S** [comment]
Yes, you are right.

Typically, I upload to Github and CTAN simultaneously, but, maybe, I should wait with CTAN in future for some time, since you always read my new stuff accurately (and I always produce some errors...). Thank you.

**Comment by muzimuzhi** [comment]
Just saw the appended staff. My "review" is not always in time so either way is ok.

**Comment by T-F-S** [comment]
Resolved in https://github.com/T-F-S/incgraph/releases/tag/v1.3.0
